### PR TITLE
Bump to Angular 16

### LINKED ISSUE #96: Work with local deps
Hi,

Now that angular 16 is released, this package needs some updates... However, users of this package could be very different versions of angular. What's the proper config to make this package use local node_modules? This should probably be in the README.

An easy workaround for the moment, for users of this package, is to extract this package and manually update the `package.json` in `server/` to their angular version and typescript version.

Thanks for this package!

### PR DESCRIPTION
**Pull request by princemaple**
close #96

### CODE REVIEW

**Comment by princemaple** [comment]
Can I get maintainer access to this repo? @predragnikolic @rchl

**Comment by predragnikolic** [comment]
@princemaple yes,
I will give you access tomorrow

**Review by predragnikolic — COMMENTED** [review]
There is a new option that was added in v15.2.0
https://github.com/angular/vscode-ng-language-service/blob/main/CHANGELOG.md#1520-next0

But because LSP-angular doesn't have a sublime-package.json file, i guess we don't have to add it in that file.

**Comment by rchl** [comment]
Will this version only be compatible with projects that use Angular 16 or also the previous versions? Or does the server use dependencies from the project?

**Comment by predragnikolic** [comment]
@princemaple I've send you a invitation to be a maintainer for this repo.

Thanks for the initiative!

**Comment by princemaple** [comment]
@rchl This most likely destroys it for previous versions.

Ideally we should allow configuration for these values https://github.com/sublimelsp/LSP-angular/blob/master/LSP-angular.sublime-settings#L3C35-L7

`server_path` and `server_directory_path`.

- Skip package installation if a customized path is set. Maybe prompt for user to run `npm install` themselves if the customized path doesn't have the packages actually installed.
- Not every project has their `node_modules` at root, e.g. some mono-repos with multiple languages or multiple projects

**Comment by princemaple** [comment]
Without the said configuration, basically everyone who's not on the current version of lsp-angular is on needs to do this workaround https://github.com/sublimelsp/LSP-angular/issues/96.

**Comment by princemaple** [comment]
@rchl Any guidance on whether/how that can be achieved? 😄

**Comment by predragnikolic** [comment]
I would say that users could override the `command` (preferably in a ST project file) to point to a locally installed angular lsp server. 

Maybe we should just give an example in the readme on how to do that.

https://github.com/sublimelsp/LSP-angular/blob/706a02996949ab923fb777562ca6f7f23b71e52c/LSP-angular.sublime-settings#L3

**Comment by princemaple** [comment]
Yeah an example of overwriting the whole command might just do the job.

**Comment by princemaple** [comment]
Angular projects are generated with `@angular/language-service` but not `@angular/language-server`. In case where a user is using a incompatible version, we'd like to support their self-installed server.

Actually another option came into mind. Maybe we can have

- `server-16/`
- `server-15/`
- `server-14/`
- etc

And allow users to pick one? default to the latest. So they don't have to install a separate server, and we re-use most of our existing logic, only changing a path.

**Comment by princemaple** [comment]
What do you think @predragnikolic ? I think this would be the easiest to use.

> Actually another option came into mind. Maybe we can have
> 
>     * `server-16/`
>     * `server-15/`
>     * `server-14/`
>     * etc

Have respective `package.json` and `package-lock.json` in them.

Now, if I understood the code correctly, we just need to read an angular version from the settings and change this variable https://github.com/sublimelsp/LSP-angular/blob/master/plugin.py#L15 and we will be able to handle any version of angular (given that we have the respective folder of package.json)

**Comment by princemaple** [comment]
😄 take all the time you need.

**Comment by predragnikolic** [comment]
Hello, 
I would not add additional settings to this package to select the Angular version. 
I don't want to add that responsibility here.

Let this package always ship the latest server. (We will also probably add a sublime-package.json file in the future, to improve the settings auto completion)

For people who need an older version of the angular server, 
I would put in the README a section, on how to point to a local  `@angular/language-server`.


They can override the start command in a ST project file, to point to a local `@angular/language-server`
```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings": {
        "LSP": {
            "LSP-angular": {
                "command": [
                    "${node_bin}",
                    "${folder}/node_modules/@angular/language-server/index.js", // maybe adjust the path based on your project
                    "--ngProbeLocations", "${folder}/node_modules",  // maybe adjust the path based on your project
                    "--tsProbeLocations", "${folder}/node_modules",  // maybe adjust the path based on your project
                    "--stdio"
                ]
            },
        }
    }
}
```

They just need to **make sure** that the  `@angular/language-server` lib is compatible with the typescript version in the project.

I experienced a typescript mismatch right away :D 
because I installed a @angular/language-server that required an older version of typescript...
I noticed the error immediately in the LSP log panel:

```
LSP-angular: /home/predragnikolic/Documents/sandbox/ang-app/node_modules/@angular/language-server/index.js:157
LSP-angular:       throw new Error(`Failed to resolve '${packageName}' with minimum version '${minVersion}' from ` + JSON.stringify(probeLocations, null, 2));
LSP-angular:       ^
LSP-angular: 
LSP-angular: Error: Failed to resolve 'typescript/lib/tsserverlibrary' with minimum version '4.2' from []
```

Other people will probably not notice this error,
They will just see `The LSP-angular server crached 5 times in 180 sec.`
 and probably won't know what is wrong. 
So they need to make sure that the versions between typescript and @angular/language-server are compatible,
if the server fails to start, the best would be to check the log panel for additional info.

**Comment by predragnikolic** [comment]
What do you guys think?

**Comment by princemaple** [comment]
> They just need to **make sure** that the `@angular/language-server` lib is compatible with the typescript version in the project.

This is the reason why I suggested preparing the `package.json` files for different angular versions, so that the users wouldn't have to do anything but specifying the angular version.

```
server-16/
|-- package.json - specifies angular 16 and ts 5.0
|-- package-lock.json - npm generated
server-15/
|-- package.json - specifies angular 15 and ts 4.8
|-- package-lock.json - npm generated
...
...
...
```

And read a setting (which defaults to the latest angular version, 16 for now) to dyanmically set this variable https://github.com/sublimelsp/LSP-angular/blob/master/plugin.py#L15

If this is not desired, then I guess we just need to merge this PR as is and add some README instructions.

This really doesn't affect me, as I'm always on the latest version. 😄

**Comment by princemaple** [comment]
Actually do we even need typescript in the `package.json`?

**Comment by Klaster1** [comment]
Any updates?

**Comment by Klaster1** [comment]
Well, I already worked around the issue by installing TS 5 and language server 16 into a separate dir and changing the LSP-angular command, but I figured it would be OK to nudge the PR a bit 😉

**Pull request merged**
