### PR TITLE
Fix: Install server outside of the cache directory

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by ihodex** [comment]
@rchl Currently working on the same :) Rafal, can you tell me how properly get the path of `server_directory` with `install_in_cache: False`?

```
ng_log_location = os.path.join(cls.package_storage(), <...>, cls.server_directory, "ngls.log")
ng_probe_location = os.path.join(cls.package_storage(), <...>, cls.server_directory, "node_modules")
```

**Comment by rchl** [comment]
Let's take this case as an example:

```
~/.../Package Storage/LSP-eslint/12.18.2/language-server/out/eslintServer.js
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cls.package_storage()
                     ^^^^^^^^^^^ cls.server_name
                                         ^^^^^^^^^^^^^^^ cls.server_directory
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cls.server_binary_path
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cls.binary_path()
```

Here are references to `binary_path()` in `npm_client_handler` and `npm_server_resource`
https://github.com/sublimelsp/lsp_utils/blob/9f7d97f938a4b61df706b054af393fb30a40c8c9/st3/lsp_utils/npm_client_handler_v2.py#L98-L99
https://github.com/sublimelsp/lsp_utils/blob/9f7d97f938a4b61df706b054af393fb30a40c8c9/st3/lsp_utils/server_npm_resource.py#L87-L88

So, in summary, I don't think that there currently exists what you want (unless you did in private properties).
We could expose something through `lsp_utils`

I'd like to see more complete example though because some of those paths can only be obtained once `ServerNpmResource` is initialized and it's done lazily so it's not necessarily that trivial.

**Comment by rchl** [comment]
But good point, I've missed that you are currently using `sublime.cache_path()` directly in:
https://github.com/sublimelsp/LSP-angular/blob/ddf97b5420544a758989032cdb1b087118098fe3/plugin.py#L21-L22

**Comment by rchl** [comment]
So if we won't care about keying logs to the used node version then we could just do:
```
ng_log_location = os.path.join(cls.package_storage(), "ngls.log")
ng_probe_location = os.path.join(cls.package_storage(), "node_modules")
```
Otherwise, the fix would need to involve changes in `lsp_utils`.

**Comment by ihodex** [comment]
oh, I see, logs aren't important, but `ng_probe_location` should be the right path to node modules

**Comment by rchl** [comment]
I've created https://github.com/sublimelsp/lsp_utils/pull/36 that adds `server_directory_path()` method to the `NpmClientHandler` class and also `$server_directory_path` variable you can use in the `command`.

Once this is integrated I would suggest defining a `command` in plugin settings like so:

```
	"command": [
		"node", "${server_path}",
		"--logFile", "${server_directory_path}/ngls.log",
		"--ngProbeLocations", "${server_directory_path}/node_modules",
		"--tsProbeLocations", "${server_directory_path}/node_modules",
		"--stdio"
	],
```

I'd like to move towards exposing `command` in all LSP plugins.

**Comment by rchl** [comment]
> I've created [sublimelsp/lsp_utils#36](https://github.com/sublimelsp/lsp_utils/pull/36) that adds `server_directory_path()` method to the `NpmClientHandler` class and also `$server_directory_path` variable you can use in the `command`.

This will be released in https://github.com/sublimelsp/lsp_utils/releases/tag/1.8.0

**Comment by ihodex** [comment]
@rchl Thanks a lot!

**Pull request merged**
